addpath('.\..\');
import CONFIG.*
import DAO.*

dao = DAO ( ...
            Config.SUBJECT_NAME, ...
            Config.TASK_NAME, ...
            Config.RESEARCHER_FIRST_NAME, ...
            Config.RESEARCHER_LAST_NAME, ...
            Config.TIME_START, ...
            Config.TIME_END, ...
            Config.BAR_SAMPLING_FREQ, ...
            Config.CLOSE_FIG_FLAG, ...
            Config.DATA_PATH ...
        );

dao.extract_experiments_data();
