close all;
clear all;
clc;

load('/home/a1/sahar/IPM/PhotoDiod/lfp.mat');

continueous_data = NS5.Data(1,:);
continueous_data_time = NS5.time_;

Trials = Trials(1:end-1);

Experiments.Plot.plot_lfp_sparse_noise( ...
                    continueous_data, ...
                    continueous_data_time, ...
                    Trials, ...
                    -500, ...
                    500, ...
                    10000*[-0.05 -0.025 0 0.025 0.05] ...
);
