classdef StimulusVariablesExperiment < Experiments.Experiment

    properties (Access = public)
        stimulus_variable_values
    end

    methods (Access = public)
        function this = StimulusVariablesExperiment ( ...
                postfix, ...
                exType, ...
                exSubject, ...
                exResearcherFN, ...
                exResearcherLN, ...
                startDate ...
        )
            this@Experiments.Experiment( ...
                                    postfix, ...
                                    exType, ...
                                    exSubject, ...
                                    exResearcherFN, ...
                                    exResearcherLN, ...
                                    startDate ...
            );
        end

        function extract_experiment_data (this, exp_index)
            this.extract_experiment_el_data(exp_index);
            this.extract_experiment_br_data();
            this.set_stimulus_variable_values(string(Experiments.StimulusVariables.get_type()));
        end

        function set_stimulus_variable_values (this, variable_name)
            variable_value_index = Utils.Util.find_last(this.Properties.info, ...
                                                      variable_name ...
            );
            variable_value_str = this.Properties.info{variable_value_index};
            this.stimulus_variable_values = ...
                eval(variable_value_str(strfind(variable_value_str, ':')+2:end)) ...
            ;
            this.stimulus_variable_values
        end

        function extract_experiment_el_data (this, exp_index)
            extract_experiment_el_data@Experiments.Experiment(this, exp_index);
        end

        function extract_experiment_br_data (this)
            extract_experiment_br_data@Experiments.Experiment(this);
        end

        function convert_properties_to_struct (this)
            convert_properties_to_struct@AnalysisData.Data(this);
        end
    end

    methods (Access = protected)

        function [start_time_eyelink,eye_time_samples] = ...
                    calibrate_times(this, events_, data_eye)
            [start_time_eyelink, eye_time_samples] = ...
                calibrate_times@Experiments.Experiment(this, events_, data_eye) ...
            ;
        end

        function set_experiment_properties (this, events_, trials_start_indices)
            set_experiment_properties@Experiments.Experiment( ...
                                                        this, ...
                                                        events_, ...
                                                        trials_start_indices ...
            );
        end

        function filter_good_trials (this)
            filter_good_trials@Experiments.Experiment(this);
        end
    end

end
