classdef OrientationTrial < AnalysisData.Trial
    properties (Access = public)
        stimulus_name
        stimulus_number_in_trial
        real_stimulus_show_time
        failed_trial
        reward
    end

    methods (Access = public)
        function extract_trial_data ( ...
                                this, ...
                                trial_index, ...
                                experiment_events, ...
                                experiment_properties, ...
                                experiment_start_date, ...
                                trials_start_indices, ...
                                eye_time_samples, ...
                                data_eye, ...
                                start_time_eyelink ...
        )
            extract_trial_data@AnalysisData.Trial( ...
                                    this, ...
                                    trial_index, ...
                                    experiment_events, ...
                                    experiment_properties, ...
                                    experiment_start_date, ...
                                    trials_start_indices, ...
                                    eye_time_samples, ...
                                    data_eye, ...
                                    start_time_eyelink ...
            );
            display_indices = Utils.Util.find_all(this.trial_events.info, 'display');
            this.update_used_indices(display_indices);
            tracker_indices = Utils.Util.find_all(this.trial_events.info, 'tracker');
            this.update_used_indices(tracker_indices);
            keyboard_indices = Utils.Util.find_all(this.trial_events.info, 'keyboard');
            this.update_used_indices(keyboard_indices);
        end

        function set_states_of_trail (this, trial_index)
            set_states_of_trail@AnalysisData.Trial(this);
        end

        function set_goodness_and_reward_of_trial (this)
            set_goodness_and_reward_of_trial@AnalysisData.Trial(this);
        end

        function convert_properties_to_struct (this)
            convert_properties_to_struct@AnalysisData.Trial(this);
        end
    end

    methods (Access = protected)
        function update_used_indices (this, new_indices)
            update_used_indices@AnalysisData.Trial(this, new_indices);
        end
    end
end
