%% States Timings
% We will stay in a specific state for a amount of time. These timings for main
% states of the trials are kept in this class.

%% Main States
% These properties are reflecting different steps of trials.
    properties (Access = public)
        fixation
        cue
        stimulus
        keepTrigger
        releaseTrigger
        trigger
        changedStimulus

    %% Set Timings
    % This function, has the responsibility to find the time of state transmitions
    % by finding the index of that transmition from states info.
        function this = StatesTimings (states)
            this.fixation = states.time(Utils.Util.find_all( ...
                                                     states.info, ...
                                                     'startFixation_waiter=>fixation') ...
            );
            this.cue = states.time(Utils.Util.find_all( ...
                                                states.info, ...
                                                'fixation_waiter=>cue') ...
            );
            this.fixation = this.fixation(end);
            this.cue = this.cue(end);

            stimulus_type1 = states.time(Utils.Util.find_all( ...
                                                        states.info, ...
                                                        'cue_waiter=>stimulus') ...
            );
            stimulus_type2 = states.time(Utils.Util.find_all( ...
                                                        states.info, ...
                                                        'nothing_waiter=>stimulus') ...
            );
            this.stimulus = union(stimulus_type1, stimulus_type2);
            this.stimulus = this.stimulus(end);

            this.keepTrigger = states.time(Utils.Util.find_all( ...
                                                        states.info, ...
                                                        'stimulus_waiter=>keepWait') ...
            );
            this.releaseTrigger = states.time(Utils.Util.find_all( ...
                                                            states.info, ...
                                                            'stimulus_waiter=>releaseWait') ...
            );
            this.trigger = union(this.keepTrigger, this.releaseTrigger);
            this.changedStimulus = states.time(Utils.Util.find_all( ...
                                                        states.info, ...
                                                        'changedStimulus=>changedStimulus_waiter') ...
            );
        end
