classdef StatesTimings
    properties (Access = private)
        fixation
        cue
        stimulus
        keepTrigger
        releaseTrigger
        trigger
        changedStimulus
    end

    methods (Access = public)
        function this = StatesTimings (states)
            this.fixation = states.time(find(cellfun(@(x) ~isempty(x), ...
                                            strfind( ...
                                                    states.info, ...
                                                    'startFixation_waiter=>fixation' ...
                                            ) ...
                            )));
            this.cue = states.time(find(cellfun(@(x) ~isempty(x), ...
                                            strfind( ...
                                                    states.info, ...
                                                    'fixation_waiter=>cue' ...
                                            ) ...
                            )));
            this.fixation = this.fixation(end);
            this.cue      = this.cue(end);

            stimulus_type1 = states.time(find(cellfun(@(x) ~isempty(x), ...
                                            strfind( ...
                                                    states.info, ...
                                                    'cue_waiter=>stimulus' ...
                                            ) ...
                            )));
            stimulus_type2 = states.time(find(cellfun(@(x) ~isempty(x), ...
                                            strfind( ...
                                                    states.info, ...
                                                    'nothing_waiter=>stimulus' ...
                                            ) ...
                            )));
            this.stimulus = union(stimulus_type1, stimulus_type2);
            this.stimulus = this.stimulus(end);

            this.keepTrigger = states.time(find(cellfun(@(x) ~isempty(x), ...
                                                strfind( ...
                                                        states.info, ...
                                                        'stimulus_waiter=>keepWait' ...
                                                ) ...
                                )));
            this.releaseTrigger = states.time(find(cellfun(@(x) ~isempty(x), ...
                                                strfind( ...
                                                        states.info, ...
                                                        'stimulus_waiter=>releaseWait' ...
                                                ) ...
                                )));
            this.trigger          = union(this.keepTrigger, this.releaseTrigger);
            this.changedStimulus = states.time(find(cellfun(@(x) ~isempty(x), ...
                                                strfind( ...
                                                        states.info, ...
                                                        'changedStimulus=>changedStimulus_waiter' ...
                                                ) ...
                                )));
        end
    end 
end
