close all
clear all

load('E:\\IPM\\EyeLink_DataExtraction\\RefactoredCodes\\output\\StimulusVariables\\Chiko\\15-Aug-2018-16-03-52-a11asz4\\data.mat');

stimulus_variable_name = string(Experiments.StimulusVariables.get_type());

Experiments.Plot.raster_plot_and_psth_of_spikes( ...
                        experiment.stimulus_variable_values, ...
                        experiment.trials, ...
                        CONFIG.Config.STIMULUS_VARIABLE_NAME, ...
                        -1000, ...
                        2000, ...
                        10000*[-0.1 -0.05 0 0.02 0.05 0.1 0.15 0.2] ...
);
