close all
clear all

experiment = load('file_name.mat');

stimulus_variable_name = Experiments.StimulusVariables.get_type();

Experiments.Plot.raster_plot_and_psth_of_spikes( ...
                        experiment.stimulus_variable_name, ...
                        experiment.trials, ...
                        CONFIG.Config.STIMULUS_VARIABLE_NAME, ...
                        -1000, ...
                        2000, ...
                        10000*[-0.1 -0.05 0 0.02 0.05 0.1 0.15 0.2] ...
);
